# Generated by Django 4.0.6 on 2022-07-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacydatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='strength',
            field=models.FloatField(default=0),
        ),
    ]
