# Generated by Django 4.0.6 on 2022-07-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacydatabase', '0002_drug_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
    ]
