# Generated by Django 4.0.6 on 2022-07-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacydatabase', '0003_pharmacy_city_pharmacy_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='gmaplink',
            field=models.CharField(default='https://maps.google.com', max_length=300),
        ),
    ]
