# Generated by Django 4.0.6 on 2022-07-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacydatabase', '0004_pharmacy_gmaplink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='milligrams',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='strength',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
