# Generated by Django 4.0.6 on 2022-07-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacydatabase', '0005_alter_drug_milligrams_alter_drug_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
