# Generated by Django 4.0.6 on 2022-07-24 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacydatabase', '0007_remove_drug_strength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='name',
        ),
    ]
