# Generated by Django 4.0.6 on 2022-07-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacydatabase', '0008_remove_drug_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
