# Generated by Django 4.0.6 on 2022-07-24 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacydatabase', '0009_drug_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='city',
            new_name='area',
        ),
    ]
