# Generated by Django 4.0.6 on 2022-07-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacydatabase', '0010_rename_city_pharmacy_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='adress',
            field=models.CharField(max_length=100),
        ),
    ]
