# Generated by Django 4.0.6 on 2022-07-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacydatabase', '0011_alter_pharmacy_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='longitude',
        ),
    ]
