# Generated by Django 4.0.6 on 2022-07-24 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('pharmacydatabase', '0013_pharmacy_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='pharmacymanager',
            field=models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='pages.pharmacymanager'),
        ),
    ]
