# Generated by Django 4.0.6 on 2022-07-24 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('pharmacydatabase', '0014_pharmacy_pharmacymanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='pharmacymanager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.pharmacymanager'),
        ),
    ]
